schema:
  - http://localhost:8080/v1/graphql
documents:
  - 'src/**/*.graphql'
generates:
  src/utils/__generated__/graphql.ts:
    plugins:
      - 'typescript'
      - 'typescript-operations'
      - 'typescript-react-apollo'
    config:
      withRefetchFn: true